### ISSUE TITLE
No symbol shown beside 'Home screen installation'

### ISSUE THREAD

**Issue by gytdau** [NOtherDev/whatwebcando#10]
The 'Home screen installation' item under 'Behave like a native app' has no tag.
![Bug](http://i.imgur.com/dMpOAhI.png)

If not having a tag was meant to convey 'this item is not applicable to your system', then a question mark symbol might do a better job instead.

**Comment by NOtherDev** [comment]
Not having a tag conveys "There's no way to check if your browser supports the feature". I don't want to do browser sniffing as it requires constant updating and I find it inaccurate and there is no way to detect the support otherwise, as I linked [in the similar issue](https://github.com/NOtherDev/whatwebcando/issues/4). In which way the question mark would be somehow better than not having any icon at all?

**Comment by gytdau** [comment]
I was thinking that you could have a blue [question mark in a circle](https://materialdesignicons.com/icon/help-circle) and then add that in the legend as something along the lines of 'Unknown support'. It's better than nothing, and it provides a bit of context instead of having no icon.

**Comment by TraderStf** [comment]
Same on Macintosh Safari, Firefox and Chrome.

**Comment by NOtherDev** [comment]
Solved with `window.BeforeInstallPromptEvent` test.
