### ISSUE TITLE
NFC API not supported

### ISSUE THREAD

**Issue by iqbal21** [NOtherDev/whatwebcando#31]
I've tried the code on the NFC sample page. But I get an error "NFC API not supported". What solution should be done to solve the error? I use LG G5 mobile phone to do testing, with NFC condition is on.

**Comment by NOtherDev** [comment]
Well you can't solve it by now because no stable browser implements Web NFC yet, so even if your Android has NFC support and it is enabled, your Chrome doesn't use it to provide NFC capabilities to the websites yet.

[NFC page at WhatWebCanDo](https://whatwebcando.today/nfc.html) suggests it is to be available "late 2016" but it looks it hadn't happened. I have a Chromium build that have this enabled, but latest Chrome Dev doesn't have it. Maybe @kenchris can help here?

**Comment by kenchris** [comment]
It is behind a flag for now, but we are in the process or making it become part of origin trial.

Just turn on the flag in about:flags - depending on your chrome release it will be a specific web nfc flag or just the generic experimental web platform features

**Comment by NOtherDev** [comment]
Thanks @kenchris for clarification. I've updated the feature description.
